version: '3.9'

services:
  judge0-server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-db:
    image: postgres:13
    env_file: judge0.conf
    restart: always
    volumes:
      - judge0-db-data:/var/lib/postgresql/data

  judge0-redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

volumes:
  judge0-db-data:
