version: '3.9'

services:
  judge0-server:
    image: judge0/judge0:1.13.1
    container_name: judge0-server
    env_file:
      - judge0.conf
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-worker:
    image: judge0/judge0:1.13.1
    container_name: judge0-worker
    command: ["./scripts/workers"]
    env_file:
      - judge0.conf
    privileged: true
    restart: always
    depends_on:
      - judge0-db
      - judge0-redis

  judge0-db:
    image: postgres:16
    container_name: judge0-db
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
    restart: always
    volumes:
      - judge0-db-data:/var/lib/postgresql/data

  judge0-redis:
    image: redis:7
    container_name: judge0-redis
    restart: always

volumes:
  judge0-db-data:
